[project]
site_name = "midas NFX GUI Manual"
site_description = "midas NFX GUI Manual"
docs_dir = "docs"
site_dir = "site"
use_directory_urls = true

nav = [
    { "결과분석" = [
        { "고급" = "결과분석/고급.md" },
        { "도구" = "결과분석/도구.md" },
        { "보이기/감추기" = "결과분석/보이기_감추기.md" },
        { "일반" = "결과분석/일반.md" },
        { "최적설계후처리" = "결과분석/최적설계후처리.md" },
        { "특수후처리" = "결과분석/특수후처리.md" }
    ] },
    { "구조 정적해석" = [
        { "공통조건" = [
            { "구속조건" = "구조_정적해석/공통조건/구속조건.md" },
            { "구속조건방정식" = "구조_정적해석/공통조건/구속조건방정식.md" },
            { "구조함수정의" = [
                { "PSD 함수" = "구조_정적해석/공통조건/구조함수정의/PSD_함수.md" },
                { "S-N 곡선 함수" = "구조_정적해석/공통조건/구조함수정의/S-N_곡선_함수.md" },
                { "건조수축함수" = "구조_정적해석/공통조건/구조함수정의/건조수축함수.md" },
                { "모달감쇠 함수" = "구조_정적해석/공통조건/구조함수정의/모달감쇠_함수.md" },
                { "비선형탄성함수" = "구조_정적해석/공통조건/구조함수정의/비선형탄성함수.md" },
                { "비열함수 (온도의존)" = "구조_정적해석/공통조건/구조함수정의/비열함수_(온도의존).md" },
                { "소성 경화 함수" = "구조_정적해석/공통조건/구조함수정의/소성_경화_함수.md" },
                { "시간의존함수" = "구조_정적해석/공통조건/구조함수정의/시간의존함수.md" },
                { "열전도율함수 (온도의존)" = "구조_정적해석/공통조건/구조함수정의/열전도율함수_(온도의존).md" },
                { "응답스텍트럼함수" = "구조_정적해석/공통조건/구조함수정의/응답스텍트럼함수.md" },
                { "응력-변형률 함수" = "구조_정적해석/공통조건/구조함수정의/응력-변형률_함수.md" },
                { "일반 공간 함수" = "구조_정적해석/공통조건/구조함수정의/일반_공간_함수.md" },
                { "일반 함수" = "구조_정적해석/공통조건/구조함수정의/일반_함수.md" },
                { "일반 함수 3D" = "구조_정적해석/공통조건/구조함수정의/일반_함수_3D.md" },
                { "전위 전도율 함수 (온도의존)" = "구조_정적해석/공통조건/구조함수정의/전위_전도율_함수_(온도의존).md" },
                { "주파수 함수" = "구조_정적해석/공통조건/구조함수정의/주파수_함수.md" },
                { "질량밀도함수 (온도의존))" = "구조_정적해석/공통조건/구조함수정의/질량밀도함수_(온도의존)).md" },
                { "크리프건조수축함수" = "구조_정적해석/공통조건/구조함수정의/크리프건조수축함수.md" },
                { "크리프함수" = "구조_정적해석/공통조건/구조함수정의/크리프함수.md" },
                { "탄성계수 함수 (온도의존)" = "구조_정적해석/공통조건/구조함수정의/탄성계수_함수_(온도의존).md" },
                { "탄성계수함수" = "구조_정적해석/공통조건/구조함수정의/탄성계수함수.md" },
                { "피로하중 함수" = "구조_정적해석/공통조건/구조함수정의/피로하중_함수.md" }
            ] },
            { "로터정의" = "구조_정적해석/공통조건/로터정의.md" },
            { "접촉조건" = [
                { "수동접촉" = "구조_정적해석/공통조건/접촉조건/수동접촉.md" },
                { "자동접촉" = "구조_정적해석/공통조건/접촉조건/자동접촉.md" },
                { "자체접촉" = "구조_정적해석/공통조건/접촉조건/자체접촉.md" },
                { "접촉관리" = "구조_정적해석/공통조건/접촉조건/접촉관리.md" },
                { "파라미터" = "구조_정적해석/공통조건/접촉조건/파라미터.md" }
            ] },
            { "체결조건" = "구조_정적해석/공통조건/체결조건.md" }
        ] },
        { "구조정적하중" = [
            { "Untitled" = "구조_정적해석/구조정적하중/untitled.md" },
            { "변위" = "구조_정적해석/구조정적하중/변위.md" },
            { "압력" = [
                { "면압력" = "구조_정적해석/구조정적하중/압력/면압력.md" },
                { "보요소압력" = "구조_정적해석/구조정적하중/압력/보요소압력.md" },
                { "파이프내압" = "구조_정적해석/구조정적하중/압력/파이프내압.md" }
            ] },
            { "열팽창변위" = [
                { "보요소온도" = "구조_정적해석/구조정적하중/열팽창변위/보요소온도.md" },
                { "쉘요소온도" = "구조_정적해석/구조정적하중/열팽창변위/쉘요소온도.md" },
                { "절점온도" = "구조_정적해석/구조정적하중/열팽창변위/절점온도.md" }
            ] },
            { "중력" = "구조_정적해석/구조정적하중/중력.md" },
            { "초기하중" = [
                { "초기/힘 스트레스" = "구조_정적해석/구조정적하중/초기하중/초기_힘_스트레스.md" },
                { "프리텐션" = "구조_정적해석/구조정적하중/초기하중/프리텐션.md" }
            ] },
            { "하중" = [
                { "리모트하중" = "구조_정적해석/구조정적하중/하중/리모트하중.md" },
                { "베어링하중" = "구조_정적해석/구조정적하중/하중/베어링하중.md" },
                { "봁하중" = "구조_정적해석/구조정적하중/하중/봁하중.md" },
                { "종동력" = "구조_정적해석/구조정적하중/하중/종동력.md" },
                { "집중하중" = "구조_정적해석/구조정적하중/하중/집중하중.md" }
            ] },
            { "회전력" = [
                { "모멘트" = "구조_정적해석/구조정적하중/회전력/모멘트.md" },
                { "토크" = "구조_정적해석/구조정적하중/회전력/토크.md" },
                { "회전관성력" = "구조_정적해석/구조정적하중/회전력/회전관성력.md" }
            ] }
        ] },
        { "구조해석열전달/줄발열(정상상태)" = [
            { "고정온도" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/고정온도.md" },
            { "공동복사" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/공동복사.md" },
            { "대류" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/대류.md" },
            { "발열" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/발열.md" },
            { "복사" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/복사.md" },
            { "열유속" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/열유속.md" },
            { "전류" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/전류.md" },
            { "전위" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/전위.md" },
            { "파이프냉각" = "구조_정적해석/구조해석열전달_줄발열(정상상태)/파이프냉각.md" }
        ] },
        { "도구" = [
            { "결과 변환" = "구조_정적해석/도구/결과_변환.md" },
            { "하중 조합" = "구조_정적해석/도구/하중_조합.md" }
        ] }
    ] },
    { "구조동적해석" = [
        { "구조 해석 열전달/줄발열(과도상태)" = [
            { "고정온도" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/고정온도.md" },
            { "공동복사" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/공동복사.md" },
            { "대류" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/대류.md" },
            { "발열" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/발열.md" },
            { "복사" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/복사.md" },
            { "열유속" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/열유속.md" },
            { "전류" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/전류.md" },
            { "전위" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/전위.md" },
            { "파이프냉각" = "구조동적해석/구조_해석_열전달_줄발열(과도상태)/파이프냉각.md" }
        ] },
        { "구조동적해석" = [
            { "시간의존" = [
                { "시간의존 절점가속도" = "구조동적해석/구조동적해석/시간의존/시간의존_절점가속도.md" },
                { "시간의존 절점변위" = "구조동적해석/구조동적해석/시간의존/시간의존_절점변위.md" },
                { "시간의존 절점속도" = "구조동적해석/구조동적해석/시간의존/시간의존_절점속도.md" },
                { "시간의존 절점하중" = "구조동적해석/구조동적해석/시간의존/시간의존_절점하중.md" }
            ] },
            { "응답스펙트럼" = "구조동적해석/구조동적해석/응답스펙트럼.md" },
            { "주파수의존" = [
                { "주파수의존 절점가속도" = "구조동적해석/구조동적해석/주파수의존/주파수의존_절점가속도.md" },
                { "주파수의존 절점변위" = "구조동적해석/구조동적해석/주파수의존/주파수의존_절점변위.md" },
                { "주파수의존 절점속도" = "구조동적해석/구조동적해석/주파수의존/주파수의존_절점속도.md" },
                { "주파수의존 절점하중" = "구조동적해석/구조동적해석/주파수의존/주파수의존_절점하중.md" }
            ] },
            { "초기속도" = "구조동적해석/구조동적해석/초기속도.md" }
        ] },
        { "도구" = [
            { "결과변환" = "구조동적해석/도구/결과변환.md" },
            { "센서정의" = "구조동적해석/도구/센서정의.md" }
        ] }
    ] },
    { "도구" = [
        { "3D PDF 내보내기" = "도구/3D_PDF_내보내기.md" },
        { "midas NFX 프로그램 정보" = "도구/midas_NFX_프로그램_정보.md" },
        { "보이기/감추기" = "도구/보이기_감추기.md" },
        { "색상" = "도구/색상.md" },
        { "옵션" = "도구/옵션.md" },
        { "절점/요소" = "도구/절점_요소.md" },
        { "정렬" = "도구/정렬.md" }
    ] },
    { "요소망" = [
        { "FE 모델" = [
            { "ABAQUS" = "요소망/FE_모델/ABAQUS.md" },
            { "NFX" = "요소망/FE_모델/NFX.md" },
            { "Nastran" = "요소망/FE_모델/Nastran.md" }
        ] },
        { "도구" = [
            { "번호수정" = "요소망/도구/번호수정.md" },
            { "요소측정" = "요소망/도구/요소측정.md" },
            { "테이블" = [
                { "요소테이블" = "요소망/도구/테이블/요소테이블.md" },
                { "절점테이블" = "요소망/도구/테이블/절점테이블.md" }
            ] },
            { "품질검사" = "요소망/도구/품질검사.md" },
            { "형상연결" = "요소망/도구/형상연결.md" }
        ] },
        { "요소 생성제어" = [
            { "레이어" = "요소망/요소_생성제어/레이어.md" },
            { "시드매칭" = "요소망/요소_생성제어/시드매칭.md" },
            { "시드제어" = "요소망/요소_생성제어/시드제어.md" }
        ] },
        { "요소생성" = [
            { "1D" = "요소망/요소생성/1D.md" },
            { "2D" = "요소망/요소생성/2D.md" },
            { "3D" = "요소망/요소생성/3D.md" },
            { "기타" = "요소망/요소생성/기타.md" },
            { "추출" = [
                { "단면스윕" = "요소망/요소생성/추출/단면스윕.md" },
                { "스윕" = "요소망/요소생성/추출/스윕.md" },
                { "옵셋" = "요소망/요소생성/추출/옵셋.md" },
                { "채우기" = "요소망/요소생성/추출/채우기.md" },
                { "추출" = "요소망/요소생성/추출/추출.md" },
                { "투영" = "요소망/요소생성/추출/투영.md" },
                { "회전" = "요소망/요소생성/추출/회전.md" }
            ] }
        ] },
        { "재료/특성" = [
            { "복합단면" = "요소망/재료_특성/복합단면.md" },
            { "재료" = "요소망/재료_특성/재료.md" },
            { "특성" = "요소망/재료_특성/특성.md" }
        ] },
        { "절점/요소 수정" = [
            { "요소" = [
                { "생성" = "요소망/절점_요소_수정/요소/생성.md" },
                { "스무드" = "요소망/절점_요소_수정/요소/스무드.md" },
                { "요소수정" = "요소망/절점_요소_수정/요소/요소수정.md" },
                { "하위요소" = "요소망/절점_요소_수정/요소/하위요소.md" },
                { "형상수정" = "요소망/절점_요소_수정/요소/형상수정.md" }
            ] },
            { "요소분할" = "요소망/절점_요소_수정/요소분할.md" },
            { "이동/복사" = "요소망/절점_요소_수정/이동_복사.md" },
            { "재생성" = [
                { "2D —> 3D" = "요소망/절점_요소_수정/재생성/2D_—__3D.md" },
                { "시드재생성" = "요소망/절점_요소_수정/재생성/시드재생성.md" },
                { "유체/구조 변환" = "요소망/절점_요소_수정/재생성/유체_구조_변환.md" },
                { "재생성" = "요소망/절점_요소_수정/재생성/재생성.md" },
                { "필렛용접" = "요소망/절점_요소_수정/재생성/필렛용접.md" }
            ] },
            { "절점" = [
                { "병합" = "요소망/절점_요소_수정/절점/병합.md" },
                { "삭제" = "요소망/절점_요소_수정/절점/삭제.md" },
                { "절점추가" = "요소망/절점_요소_수정/절점/절점추가.md" },
                { "정렬" = "요소망/절점_요소_수정/절점/정렬.md" },
                { "좌표계" = "요소망/절점_요소_수정/절점/좌표계.md" },
                { "투영" = "요소망/절점_요소_수정/절점/투영.md" }
            ] },
            { "절점연결" = "요소망/절점_요소_수정/절점연결.md" },
            { "파라미터" = "요소망/절점_요소_수정/파라미터.md" }
        ] }
    ] },
    { "유동해석" = [
        { "공통조건" = [
            { "유동함수 정의" = [
                { "CFD 수식 함수" = "유동해석/공통조건/유동함수_정의/CFD_수식_함수.md" },
                { "CFD 테이블 함수" = "유동해석/공통조건/유동함수_정의/CFD_테이블_함수.md" },
                { "산란위상함수" = "유동해석/공통조건/유동함수_정의/산란위상함수.md" },
                { "연결함수" = "유동해석/공통조건/유동함수_정의/연결함수.md" },
                { "저항곡선 함수" = "유동해석/공통조건/유동함수_정의/저항곡선_함수.md" },
                { "편곡선 함수" = "유동해석/공통조건/유동함수_정의/편곡선_함수.md" }
            ] },
            { "접촉조건" = [
                { "수동접촉" = "유동해석/공통조건/접촉조건/수동접촉.md" },
                { "자동접촉" = "유동해석/공통조건/접촉조건/자동접촉.md" },
                { "파라미터" = "유동해석/공통조건/접촉조건/파라미터.md" }
            ] }
        ] },
        { "도구" = [
            { "결과 변환" = "유동해석/도구/결과_변환.md" },
            { "모니터링" = "유동해석/도구/모니터링.md" }
        ] },
        { "유동 해석 열전달/줄발열" = [
            { "고정온도" = "유동해석/유동_해석_열전달_줄발열/고정온도.md" },
            { "공동복사" = "유동해석/유동_해석_열전달_줄발열/공동복사.md" },
            { "대류" = "유동해석/유동_해석_열전달_줄발열/대류.md" },
            { "발열" = "유동해석/유동_해석_열전달_줄발열/발열.md" },
            { "복사" = "유동해석/유동_해석_열전달_줄발열/복사.md" },
            { "복사벽면" = "유동해석/유동_해석_열전달_줄발열/복사벽면.md" },
            { "열유속" = "유동해석/유동_해석_열전달_줄발열/열유속.md" },
            { "열저항 모델" = "유동해석/유동_해석_열전달_줄발열/열저항_모델.md" },
            { "전류" = "유동해석/유동_해석_열전달_줄발열/전류.md" },
            { "전위" = "유동해석/유동_해석_열전달_줄발열/전위.md" },
            { "태양열 변면" = "유동해석/유동_해석_열전달_줄발열/태양열_변면.md" }
        ] },
        { "읿반 유동해석" = [
            { "1D 배관" = [
                { "2점 연결" = "유동해석/읿반_유동해석/1D_배관/2점_연결.md" },
                { "다절점 연결" = "유동해석/읿반_유동해석/1D_배관/다절점_연결.md" },
                { "대류" = "유동해석/읿반_유동해석/1D_배관/대류.md" },
                { "압력" = "유동해석/읿반_유동해석/1D_배관/압력.md" },
                { "열교환" = "유동해석/읿반_유동해석/1D_배관/열교환.md" },
                { "열유속" = "유동해석/읿반_유동해석/1D_배관/열유속.md" },
                { "온도" = "유동해석/읿반_유동해석/1D_배관/온도.md" },
                { "유체 커플링" = "유동해석/읿반_유동해석/1D_배관/유체_커플링.md" },
                { "유체용기" = "유동해석/읿반_유동해석/1D_배관/유체용기.md" },
                { "입구단" = "유동해석/읿반_유동해석/1D_배관/입구단.md" },
                { "출구단" = "유동해석/읿반_유동해석/1D_배관/출구단.md" }
            ] },
            { "다공성" = [
                { "타공판" = "유동해석/읿반_유동해석/다공성/타공판.md" }
            ] },
            { "다상유동" = [
                { "다상유동 정의" = "유동해석/읿반_유동해석/다상유동/다상유동_정의.md" },
                { "자유수면높이" = "유동해석/읿반_유동해석/다상유동/자유수면높이.md" },
                { "자유수면높이 측정면" = "유동해석/읿반_유동해석/다상유동/자유수면높이_측정면.md" },
                { "체적분율" = "유동해석/읿반_유동해석/다상유동/체적분율.md" }
            ] },
            { "벽면" = [
                { "박판" = "유동해석/읿반_유동해석/벽면/박판.md" },
                { "벽면" = "유동해석/읿반_유동해석/벽면/벽면.md" },
                { "원방경계" = "유동해석/읿반_유동해석/벽면/원방경계.md" },
                { "주기대칭" = "유동해석/읿반_유동해석/벽면/주기대칭.md" },
                { "혼합면" = "유동해석/읿반_유동해석/벽면/혼합면.md" }
            ] },
            { "이동/변위" = [
                { "벽면 이동" = "유동해석/읿반_유동해석/이동_변위/벽면_이동.md" },
                { "체적 변형" = "유동해석/읿반_유동해석/이동_변위/체적_변형.md" }
            ] },
            { "입/출구단" = [
                { "난류" = "유동해석/읿반_유동해석/입_출구단/난류.md" },
                { "유동속도" = "유동해석/읿반_유동해석/입_출구단/유동속도.md" },
                { "유동압력" = "유동해석/읿반_유동해석/입_출구단/유동압력.md" },
                { "입구단" = "유동해석/읿반_유동해석/입_출구단/입구단.md" },
                { "출구단" = "유동해석/읿반_유동해석/입_출구단/출구단.md" },
                { "팬" = "유동해석/읿반_유동해석/입_출구단/팬.md" }
            ] },
            { "파티클" = [
                { "충돌벽" = "유동해석/읿반_유동해석/파티클/충돌벽.md" },
                { "파티클 분포" = "유동해석/읿반_유동해석/파티클/파티클_분포.md" },
                { "파티클 생성" = "유동해석/읿반_유동해석/파티클/파티클_생성.md" },
                { "파티클 정의" = "유동해석/읿반_유동해석/파티클/파티클_정의.md" }
            ] },
            { "혼합물" = [
                { "물질생성율" = "유동해석/읿반_유동해석/혼합물/물질생성율.md" },
                { "물질전달율" = "유동해석/읿반_유동해석/혼합물/물질전달율.md" },
                { "질량 분율" = "유동해석/읿반_유동해석/혼합물/질량_분율.md" },
                { "혼합물 정의" = "유동해석/읿반_유동해석/혼합물/혼합물_정의.md" }
            ] }
        ] }
    ] },
    { "해석" = [
        { "도구" = [
            { "결과변환" = "해석/도구/결과변환.md" },
            { "모니터링" = "해석/도구/모니터링.md" },
            { "센서정의" = "해석/도구/센서정의.md" },
            { "옵션" = "해석/도구/옵션.md" },
            { "하중조합" = "해석/도구/하중조합.md" }
        ] },
        { "해석" = [
            { "배치해석" = "해석/해석/배치해석.md" },
            { "실행" = "해석/해석/실행.md" }
        ] },
        { "해석옵션 정의" = [
            { "구조해석" = "해석/해석옵션_정의/구조해석.md" },
            { "유동해석" = "해석/해석옵션_정의/유동해석.md" },
            { "해석설정" = "해석/해석옵션_정의/해석설정.md" }
        ] },
        { "해석케이스 정의" = [
            { "단일해석" = "해석/해석케이스_정의/단일해석.md" },
            { "연계해석" = [
                { "FSI 인터페이스" = "해석/해석케이스_정의/연계해석/FSI_인터페이스.md" },
                { "단방향 FSI" = "해석/해석케이스_정의/연계해석/단방향_FSI.md" },
                { "양방향 FSI" = "해석/해석케이스_정의/연계해석/양방향_FSI.md" }
            ] },
            { "최적화" = [
                { "구조 설계변수" = "해석/해석케이스_정의/최적화/구조_설계변수.md" },
                { "실험점 추출" = "해석/해석케이스_정의/최적화/실험점_추출.md" },
                { "위상최적설계" = "해석/해석케이스_정의/최적화/위상최적설계.md" },
                { "치수최적설계" = "해석/해석케이스_정의/최적화/치수최적설계.md" }
            ] }
        ] }
    ] },
    { "형상" = [
        { "CAD File" = [
            { "내보내기" = "형상/CAD_File/내보내기.md" },
            { "불러오기" = "형상/CAD_File/불러오기.md" }
        ] },
        { "도구" = [
            { "간략화" = "형상/도구/간략화.md" },
            { "요소-면 변환" = "형상/도구/요소-면_변환.md" },
            { "유동영역 추출" = "형상/도구/유동영역_추출.md" },
            { "자동연결" = "형상/도구/자동연결.md" },
            { "중립면 추출" = "형상/도구/중립면_추출.md" },
            { "측정" = "형상/도구/측정.md" },
            { "형상검사" = "형상/도구/형상검사.md" }
        ] },
        { "차원수 변경" = [
            { "상위형상" = "형상/차원수_변경/상위형상.md" },
            { "하위형상" = "형상/차원수_변경/하위형상.md" }
        ] },
        { "형상생성" = [
            { "면" = [
                { "다각형" = "형상/형상생성/면/다각형.md" },
                { "사각형" = "형상/형상생성/면/사각형.md" },
                { "원" = "형상/형상생성/면/원.md" },
                { "타원" = "형상/형상생성/면/타원.md" }
            ] },
            { "선" = [
                { "나선" = "형상/형상생성/선/나선.md" },
                { "선" = "형상/형상생성/선/선.md" },
                { "연결선" = "형상/형상생성/선/연결선.md" },
                { "원호" = "형상/형상생성/선/원호.md" },
                { "자유곡선" = "형상/형상생성/선/자유곡선.md" },
                { "프로파일" = "형상/형상생성/선/프로파일.md" }
            ] },
            { "솔리드" = [
                { "구" = "형상/형상생성/솔리드/구.md" },
                { "박스" = "형상/형상생성/솔리드/박스.md" },
                { "쇄기" = "형상/형상생성/솔리드/쇄기.md" },
                { "원기둥" = "형상/형상생성/솔리드/원기둥.md" },
                { "원뿔" = "형상/형상생성/솔리드/원뿔.md" },
                { "토러스" = "형상/형상생성/솔리드/토러스.md" }
            ] },
            { "작업평면" = "형상/형상생성/작업평면.md" },
            { "점" = "형상/형상생성/점.md" }
        ] },
        { "형상수정" = [
            { "면" = [
                { "교차연산" = "형상/형상수정/면/교차연산.md" },
                { "나누기" = "형상/형상수정/면/나누기.md" },
                { "면만들기" = "형상/형상수정/면/면만들기.md" },
                { "미소선 제거" = "형상/형상수정/면/미소선_제거.md" },
                { "임프린트" = "형상/형상수정/면/임프린트.md" }
            ] },
            { "선" = [
                { "교차선끊기" = "형상/형상수정/선/교차선끊기.md" },
                { "면사이의 교차선" = "형상/형상수정/선/면사이의_교차선.md" },
                { "선끊기" = "형상/형상수정/선/선끊기.md" },
                { "선병합" = "형상/형상수정/선/선병합.md" },
                { "선연장하기" = "형상/형상수정/선/선연장하기.md" },
                { "선옵셋" = "형상/형상수정/선/선옵셋.md" },
                { "선잘라내기" = "형상/형상수정/선/선잘라내기.md" },
                { "선필렛" = "형상/형상수정/선/선필렛.md" },
                { "와이어 생성" = "형상/형상수정/선/와이어_생성.md" },
                { "최단 거리 선" = "형상/형상수정/선/최단_거리_선.md" }
            ] },
            { "솔리드" = [
                { "교차연산" = "형상/형상수정/솔리드/교차연산.md" },
                { "나누기" = "형상/형상수정/솔리드/나누기.md" },
                { "옵셋" = "형상/형상수정/솔리드/옵셋.md" },
                { "필렛과 모따기" = "형상/형상수정/솔리드/필렛과_모따기.md" }
            ] },
            { "스케일" = "형상/형상수정/스케일.md" },
            { "이동" = "형상/형상수정/이동.md" },
            { "추출" = "형상/형상수정/추출.md" },
            { "투영" = [
                { "부착" = "형상/형상수정/투영/부착.md" },
                { "투영" = "형상/형상수정/투영/투영.md" }
            ] }
        ] }
    ] }
]

[project.theme]
language = "ko"
variant = "modern"
